name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install frontend & build
      - name: Build frontend
        run: |
          cd frontend
          npm install
          CI=false npm run build

      # 4. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/IFN636
            git pull origin main

            # Backend
            cd backend
            npm install

            # Frontend
            cd ../frontend
            npm install
            npm run build

            # Copy build to nginx
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r build/* /usr/share/nginx/html/

            # Restart services
            pm2 restart all
            sudo systemctl restart nginx
